services:
  app:
    image: xoom-analytics-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

    volumes:
      - ./src:/app/src
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action : rebuild
          path: requirements.txt
        - action: rebuild
          path: docker-compose.yaml
    
      

